### ISSUE TITLE
[Feature Request] None steam game detection/manual adding

### ISSUE THREAD

**Issue by SaltySamurai** [CEbbinghaus/MicroSDeck#10]
I have some games added for emulation, at the moment I just keep them all on the same card so I know where they all are, but it would be nice to be able to use the sorting features in Tab Master to see games installed on the SD card even if it's an emulated title or other none steam games that does not show up as installed.

**Comment by CEbbinghaus** [comment]
Assuming you already have the latest version of MicroSDeck installed it should theoretically just work. Tab-Master just asks MicroSDeck for the games that are on the card and should display them in the list. I have been able to show non steam games as long as they were added to MicroSDeck

**Comment by jfreuden** [comment]
I was able to reproduce this. @CEbbinghaus can you modify this to a bug, and I'll work it?
I think I have a reliable way to trigger it, as well as _maybe_ a way to workaround it such that the Non-Steam games stick around

**Comment by CEbbinghaus** [comment]
That would be awesome if you are able to reproduce it I would be eternally grateful if you posted the steps to reproduce the problems too so I can try make it happen locally too

**Comment by jfreuden** [comment]
Narrowing in on it, will post shortly. Right now it deletes all user-facing mappings almost every time I enter desktop mode and open Steam. The entry remains in the datastore, but the mapping seems invalid. When I get a cleaner repro list, I'll post here

**Comment by jfreuden** [comment]
I can't seem to figure out what last variable was triggering it 😢 . Merely going into desktop mode is not generally enough to cause the disassociation. While trying to hone in, I changed something and can't get it to pop anymore. I'll look at it more later this week unless someone else can beat me to a reliable repro.

**Comment by CEbbinghaus** [comment]
That is an amazing start. No wonder I could never repro it. I just SSH into my steamdeck so I never enter desktop mode. I will need to check with Nabel0 to see if this is what is happening to them.

**Comment by CEbbinghaus** [comment]
Hmmm, that looks fairly standard, a link between a game and a card got changed (the last 2) and the hash of one of the cards changed (which also checks out). None of this is out of the ordinary

**Comment by jfreuden** [comment]
This should have been fixed by @CEbbinghaus in [this commit](https://github.com/CEbbinghaus/MicroSDeck/commit/1e1c3155a64d98ea1c5ceab2befb690990baf804) from #14 . It should be on master / nightly builds
